export const CREATE_ITEM = "CREATE_ITEM";
export const RETRIEVE_ITEMS = "RETRIEVE_ITEMS";
export const RETRIEVE_ALL_ITEMS = "RETRIEVE_ALL_ITEMS";
export const RETRIEVE_FEATURED_ITEMS = "RETRIEVE_FEATURED_ITEMS";
export const RETRIEVE_ITEM_DETAIL = "RETRIEVE_ITEM_DETAIL";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ALL_ITEMS = "DELETE_ALL_ITEMS";

export const CREATE_CAT = "CREATE_CAT";
export const RETRIEVE_CATS = "RETRIEVE_CATS";
export const UPDATE_CAT = "UPDATE_CAT";
export const DELETE_CAT = "DELETE_CAT";
export const DELETE_ALL_CATS = "DELETE_ALL_CATS";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";